
import type { NavItem } from '@/lib/types';
import {
  BookMarked,
  BookOpenCheck,
  BookText,
  BotMessageSquare,
  BrainCircuit,
  Camera,
  Crown,
  Ear,
  FileText,
  GraduationCap,
  Handshake,
  Headset,
  Languages,
  LayoutDashboard,
  Megaphone,
  MicVocal,
  Music,
  Package,
  Scale,
  School,
  Trophy,
  User,
  UserCheck,
  Users,
} from 'lucide-react';

export const menuItems: NavItem[] = [
  { href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { href: '/learning-path', label: 'Learning Path', icon: BrainCircuit },
  { href: '/chatbot', label: 'Chatbot', icon: BotMessageSquare },
  { href: '/lesson-planner', label: 'Lesson Planner', icon: FileText },
  { href: '/exercises', label: 'Exercises', icon: BookOpenCheck },
  { href: '/accent-training', label: 'Accent Training', icon: MicVocal },
  { href: '/leitner-box', label: 'Leitner Box', icon: Package },
  { href: '/stories', label: 'Bilingual Stories', icon: BookText },
  { href: '/translation', label: 'Translation', icon: Languages },
  { href: '/listening', label: 'Listening', icon: Ear },
  { href: '/challenges', label: 'Challenges', icon: Trophy },
  { href: '/object-identifier', label: 'Object Identifier', icon: Camera },
  { href: '/community', label: 'Community', icon: Users },
  { href: '/ad-platform', label: 'Ad Platform', icon: Megaphone },
  { href: '/partners', label: 'Partners', icon: Handshake },
  { href: '/konkur-tutors', label: 'Konkur Tutors', icon: UserCheck },
  { href: '/live-classes', label: 'Live Classes', icon: School },
  { href: '/karaoke', label: 'Karaoke', icon: Music, premium: true },
  {
    href: '/ielts-toefl-prep',
    label: 'IELTS/TOEFL Prep',
    icon: GraduationCap,
    premium: true,
  },
  {
    href: '/simultaneous-interpretation',
    label: 'Simultaneous Interpretation',
    icon: Headset,
    premium: true,
  },
  { href: '/profile', label: 'Profile', icon: User },
];
