
import type { NavItem } from '@/lib/types';
import {
  Award,
  BookAudio,
  BookMarked,
  BookOpenCheck,
  BookText,
  BotMessageSquare,
  BrainCircuit,
  Building,
  Camera,
  Crown,
  Ear,
  FileText,
  Film,
  Gavel,
  Gem,
  GraduationCap,
  Handshake,
  Headset,
  Languages,
  LayoutDashboard,
  Megaphone,
  MicVocal,
  Music,
  Package,
  School,
  Swords,
  Trophy,
  User,
  UserCheck,
  Users,
} from 'lucide-react';

export const menuItems: NavItem[] = [
  { href: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { href: '/learning-path', label: 'Learning Path', icon: BrainCircuit },
  { href: '/chatbot', label: 'Chatbot', icon: BotMessageSquare },
  { href: '/community', label: 'Community', icon: Users },
  { href: '/duel-arena', label: 'Duel Arena', icon: Swords },
  { href: '/lesson-planner', label: 'AI Lesson Creator', icon: FileText },
  { href: '/exercises', label: 'Exercises', icon: BookOpenCheck },
  { href: '/accent-training', label: 'Accent Training', icon: MicVocal },
  { href: '/leitner-box', label: 'Leitner Box', icon: Package },
  { href: '/stories', label: 'Bilingual Stories', icon: BookText },
  { href: '/translation', label: 'Translation', icon: Languages },
  { href: '/listening', label: 'Listening', icon: Ear },
  { href: '/challenges', label: 'Challenges', icon: Trophy },
  { href: '/object-identifier', label: 'Object Identifier', icon: Camera },
  { href: '/monthly-awards', label: 'Monthly Awards', icon: Award },
  { href: '/bidding-hall', label: 'Bidding Hall', icon: Gavel },
  { href: '/ad-platform', label: 'Ad Platform', icon: Megaphone },
  { href: '/partners', label: 'Partners', icon: Handshake },
  { href: '/konkur-tutors', label: 'Konkur Tutors', icon: UserCheck },
  { href: '/live-classes', label: 'Live Classes', icon: School },
  { href: '/creation-story', label: 'Creation Story', icon: BookAudio },
  { href: '/philosophy-gems', label: 'Philosophy Gems', icon: Gem },
  { href: '/deployment', label: 'Headquarters', icon: Building },
  { href: '/genesis-movie', label: 'Genesis Movie', icon: Film, premium: true },
  { href: '/karaoke', label: 'Karaoke', icon: Music, premium: true },
  {
    href: '/ielts-toefl-prep',
    label: 'IELTS/TOEFL Prep',
    icon: GraduationCap,
    premium: true,
  },
  {
    href: '/simultaneous-interpretation',
    label: 'Simultaneous Interpretation',
    icon: Headset,
    premium: true,
  },
  { href: '/profile', label: 'Profile', icon: User },
];

    