
'use client';

import { useState } from 'react';
import { PageHeader } from '@/components/shared/page-header';
import { Film, Loader2, Sparkles, Wand2, Quote, Video, Download, Share2, Twitter, MessageCircle } from 'lucide-react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { generateGenesisMovie, type GenesisMovieOutput } from '@/ai/flows/genesis-movie-generation';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';

export default function GenesisMoviePage() {
  const [userQuote, setUserQuote] = useState('');
  const [generatedMovie, setGeneratedMovie] = useState<GenesisMovieOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleGenerateMovie = async () => {
    if (!userQuote.trim()) {
      toast({
        variant: 'destructive',
        title: 'Quote is missing',
        description: 'Please enter a sentence or idea to inspire your movie.',
      });
      return;
    }
    setIsLoading(true);
    setGeneratedMovie(null);
    toast({
      title: 'The Genesis Engine is Running...',
      description: 'The AI is crafting a cinematic vision of your idea. This is a complex process and may take up to a minute. Please be patient.',
    });
    try {
      const result = await generateGenesisMovie({ userQuote });
      setGeneratedMovie(result);
      toast({
        title: 'Your Personal Genesis Movie is Ready!',
        description: 'Witness the birth of your vision within Afarinesh.',
      });
    } catch (error) {
      console.error('Error generating movie:', error);
      toast({
        variant: 'destructive',
        title: 'Error in Creation',
        description: 'There was a problem generating the movie. The AI might be under heavy load. Please try again in a few moments.',
      });
    } finally {
      setIsLoading(false);
    }
  };
  
    const handleShare = (platform: 'twitter' | 'facebook') => {
    const text = encodeURIComponent(`I just co-created a cinematic vision in the world of Afarinesh! Witness the power of creation. My idea was: "${userQuote}"`);
    const url = encodeURIComponent('https://linguaweave.app'); // Replace with your actual app URL
    let shareUrl = '';

    if (platform === 'twitter') {
      shareUrl = `https://twitter.com/intent/tweet?text=${text}&url=${url}`;
    } else if (platform === 'facebook') {
      shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${url}&quote=${text}`;
    }

    window.open(shareUrl, '_blank', 'noopener,noreferrer');
    toast({
        title: "Share to Earn XP!",
        description: "You'll receive bonus XP once your friends join through your shared link."
    })
  };


  return (
    <div>
      <PageHeader
        title="The Genesis Movie"
        description="Co-create an AI-powered cinematic vision of the Afarinesh philosophy."
        icon={Film}
      />
      
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <Card className="lg:col-span-2">
            <CardHeader>
                <CardTitle className="flex items-center gap-2">
                    <Video className="w-6 h-6 text-primary"/>
                    The Creator's Vision (Sample)
                </CardTitle>
                <CardDescription>This is a sample film generated by the AI, representing the core spirit of "Afarinesh".</CardDescription>
            </CardHeader>
            <CardContent>
                 <video src="/Afarinesh_Genesis_Sample.mp4" className="w-full rounded-lg border bg-muted" loop controls autoPlay muted>
                    Your browser does not support the video tag.
                </video>
            </CardContent>
            <CardFooter>
                 <p className="text-xs text-muted-foreground">This video serves as an example of what the Genesis AI can create.</p>
            </CardFooter>
        </Card>

        <Card className="lg:col-span-2">
            <CardHeader>
                 <CardTitle className="flex items-center gap-2">
                    <Sparkles className="w-6 h-6 text-accent"/>
                    Your Personal Genesis
                </CardTitle>
                <CardDescription>
                    Now, become a co-creator. Provide a meaningful sentence or idea, and the AI will weave it into a unique cinematic vision for you.
                </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
                <div className="space-y-2">
                    <Label htmlFor="user-quote">Your inspiring sentence or idea:</Label>
                    <Textarea 
                        id="user-quote"
                        value={userQuote}
                        onChange={(e) => setUserQuote(e.target.value)}
                        placeholder="e.g., 'True learning is finding the music between the notes.' or 'یک رویا، آغازی برای خلق یک جهان است.'"
                        rows={3}
                        disabled={isLoading}
                    />
                </div>
                 <Button onClick={handleGenerateMovie} size="lg" disabled={isLoading} className="w-full">
                    <Wand2 className="mr-2 h-4 w-4" />
                    {isLoading ? 'Creating Your Vision...' : 'Generate My Movie'}
                </Button>
            </CardContent>
            <CardFooter>
                 <p className="text-xs text-muted-foreground">This feature uses Google's Veo model. Video generation is a complex task and may take up to a minute.</p>
            </CardFooter>
        </Card>
        
        {(isLoading || generatedMovie) && (
             <div className="lg:col-span-2">
                 {isLoading && (
                  <div className="flex flex-col items-center justify-center min-h-[400px] border-2 border-dashed rounded-lg p-8 text-center">
                    <Loader2 className="w-12 h-12 animate-spin text-primary mb-4" />
                    <h2 className="text-xl font-semibold">Rendering your vision...</h2>
                    <p className="text-muted-foreground">This is an intensive creative process. Thank you for your patience.</p>
                  </div>
                )}
                {generatedMovie && (
                    <Card>
                        <CardHeader>
                            <CardTitle>Your Vision, Realized</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-6">
                            <video controls src={generatedMovie.videoDataUri} className="w-full rounded-lg border bg-muted" loop autoPlay>
                                Your browser does not support the video tag.
                            </video>
                             <Card>
                                <CardHeader>
                                    <CardTitle className="flex items-center gap-2 text-xl">
                                        <Share2 className="w-5 h-5"/>
                                        Share Your Creation
                                    </CardTitle>
                                    <CardDescription>Download your movie or share it with the world to earn rewards.</CardDescription>
                                </CardHeader>
                                <CardContent className="space-y-4">
                                     <Alert className="border-accent text-accent-foreground bg-accent/10">
                                        <Sparkles className="h-4 w-4 text-accent" />
                                        <AlertTitle>Earn Bonus XP!</AlertTitle>
                                        <AlertDescription>
                                            Share your creation on social media. You'll earn XP for every friend who joins Afarinesh through your link!
                                        </AlertDescription>
                                    </Alert>
                                    <div className="flex flex-col sm:flex-row gap-4">
                                        <a href={generatedMovie.videoDataUri} download={`Afarinesh-Genesis-${Date.now()}.mp4`} className="w-full">
                                            <Button className="w-full" variant="outline">
                                                <Download className="mr-2 h-4 w-4" />
                                                Download Movie
                                            </Button>
                                        </a>
                                        <div className="flex gap-4 w-full">
                                            <Button className="w-full" onClick={() => handleShare('twitter')}>
                                                <Twitter className="mr-2 h-4 w-4" />
                                                Share on X
                                            </Button>
                                             <Button className="w-full bg-[#1877F2] hover:bg-[#1877F2]/90" onClick={() => handleShare('facebook')}>
                                                <MessageCircle className="mr-2 h-4 w-4" />
                                                Share on Facebook
                                            </Button>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        </CardContent>
                    </Card>
                )}
             </div>
        )}

      </div>
    </div>
  );
}
