
'use client';

import { useState } from 'react';
import { PageHeader } from '@/components/shared/page-header';
import { Film, Loader2, Sparkles, Wand2 } from 'lucide-react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import { generateGenesisMovie, type GenesisMovieOutput } from '@/ai/flows/genesis-movie-generation';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

export default function GenesisMoviePage() {
  const [movie, setMovie] = useState<GenesisMovieOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleGenerateMovie = async () => {
    setIsLoading(true);
    setMovie(null);
    toast({
      title: 'The Genesis Engine is Running...',
      description: 'The AI is crafting a cinematic vision of our universe. This is a complex process and may take up to a minute. Please be patient.',
    });
    try {
      const result = await generateGenesisMovie();
      setMovie(result);
      toast({
        title: 'The Genesis Movie is Ready!',
        description: 'Witness the birth of Afarinesh.',
      });
    } catch (error) {
      console.error('Error generating movie:', error);
      toast({
        variant: 'destructive',
        title: 'Error in Creation',
        description: 'There was a problem generating the movie. The AI might be under heavy load. Please try again in a few moments.',
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div>
      <PageHeader
        title="The Genesis Movie"
        description="Generate a unique, AI-powered cinematic vision of the Afarinesh philosophy."
        icon={Film}
      />
      <div className="flex justify-center">
        <Card className="w-full max-w-4xl">
          <CardHeader className="text-center">
            <CardTitle className="text-2xl">The Cinematic Heart of Creation</CardTitle>
            <CardDescription>
              This is more than a video. It's a glimpse into our soul, generated in real-time by our creative AI.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {isLoading && (
              <div className="flex flex-col items-center justify-center h-full min-h-[400px] p-8 text-center">
                <Loader2 className="w-12 h-12 animate-spin text-primary mb-4" />
                <h2 className="text-xl font-semibold">Rendering the vision...</h2>
                <p className="text-muted-foreground">This is an intensive creative process. Thank you for your patience.</p>
              </div>
            )}

            {!isLoading && !movie && (
              <div className="flex flex-col items-center justify-center h-full min-h-[400px] p-8 text-center space-y-6">
                <Film className="w-12 h-12 text-muted-foreground" />
                <div className="space-y-2">
                    <h2 className="text-xl font-semibold">The Vision Awaits Your Command</h2>
                    <p className="text-muted-foreground max-w-md mx-auto">Press the button below to command the AI to generate a short, cinematic film embodying the spirit of "Afarinesh".</p>
                </div>
                 <Button onClick={handleGenerateMovie} size="lg">
                    <Wand2 className="mr-2 h-4 w-4" />
                    Generate The Genesis Movie
                </Button>
              </div>
            )}
            
            {movie && (
                <div className="space-y-4">
                    <video controls src={movie.videoDataUri} className="w-full rounded-lg border bg-muted" loop autoPlay>
                        Your browser does not support the video tag.
                    </video>
                    <Alert>
                        <Sparkles className="h-4 w-4" />
                        <AlertTitle>A Unique Creation</AlertTitle>
                        <AlertDescription>
                            This video was generated by AI just for you. Each generation is unique. Feel free to generate it again to see a new vision.
                        </AlertDescription>
                    </Alert>
                </div>
            )}
          </CardContent>
          <CardFooter>
            <p className="text-xs text-muted-foreground mx-auto">This feature uses Google's Veo model. Video generation is a complex task and may take up to a minute.</p>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}
